pygeodes.utils.exceptions.InvalidChecksumException
==================================================

.. currentmodule:: pygeodes.utils.exceptions

.. autoexception:: InvalidChecksumException